---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20136.
--- DateTime: 2025/11/16 12:18
---
local id = redis.call('get',KEYS[1])

if(id == ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0